packages:
  - 'packages/*'
  - 'examples/*'

allowBuilds:
  esbuild: true
  simple-git-hooks: true

confirmModulesPurge: false

minimumReleaseAgeExclude:
  - '@dom-expressions/babel-plugin-jsx'
  - '@dom-expressions/compiler'
  - '@dom-expressions/hyperscript'
  - '@dom-expressions/runtime'
  - '@dom-expressions/tagged-jsx'
  - '@solidjs/vite-plugin'

overrides:
  babel-preset-solid: workspace:*
  '@solidjs/signals': workspace:*
  solid-js: workspace:*
  '@solidjs/web': workspace:*
