const path = require("path");
const { runFixtures } = require("./fixtures");
const plugin = require("../index");

runFixtures({
  plugin,
  pluginOptions: {
    moduleName: "r-dom",
    builtIns: ["For", "Show"],
    generate: "dynamic",
    wrapConditionals: false,
    delegateEvents: false,
    effectWrapper: false,
    memoWrapper: false,
    contextToCustomElements: true,
    renderers: [
      {
        name: "dom",
        elements: [
          "table",
          "tbody",
          "div",
          "h1",
          "span",
          "header",
          "footer",
          "slot",
          "my-el",
          "my-element",
          "module",
          "input",
          "img",
          "iframe",
          "button",
          "a",
          "svg",
          "rect",
          "x",
          "y",
          "linearGradient",
          "stop",
          "style",
          "li",
          "ul",
          "label",
          "text",
          "namespace:tag",
          "html",
          "head",
          "body",
          "title",
          "meta",
          "link",
          "footer",
          "script",
          "noscript",
          "select",
          "option",
          "video",
          "math",
          "merror",
          "mfrac",
          "mi",
          "mmultiscripts",
          "mn",
          "mo",
          "mover",
          "mpadded",
          "mphantom",
          "mprescripts",
          "mroot",
          "mrow",
          "ms",
          "mspace",
          "msqrt",
          "mstyle",
          "msub",
          "msubsup",
          "msup",
          "mtable",
          "mtd",
          "mtext",
          "mtr",
          "munder",
          "munderover",
          "semantics",
          "menclose",
          "mfenced"
        ],
        moduleName: "r-dom"
      }
    ]
  },
  title: "Convert JSX",
  fixtures: path.join(__dirname, "__dom_wrapperless_fixtures__")
});
